project:
  type: website
  output-dir: docs


website:
  title: "Minimal Quarto Lab Book"
  sidebar:
    smooth-scroll: true
    logo: img/logo.png
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - notebook.ipynb



format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 305px
    toc: true
    number-chapters: true
    number-sections: true